name: 拉取镜像推送-tencent

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: '原镜像名称:版本'
        required: true
        default: '-'
      NEW_NAME:
        description: '同步后镜像名称:版本'
        required: true
        default: '-'
      TARGET_REGISTRY:
        description: '仓库地址'
        required: true
        default: 'ccr.ccs.tencentyun.com'
      TARGET_REPOSITORY:
        description: '空间名称'
        required: true
        default: 'xlgo'
      ARCH:
        description: '系统架构'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64
          - arm/v7
          - arm/v6
          - 386
          - s390x
          - ppc64le

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 登录到 Docker 仓库
        id: login
        run: docker login -u ${{ secrets.TENCENT_DOCKER_USERNAME }} -p ${{ secrets.TENCENT_DOCKER_PASSWORD }} ${{ github.event.inputs.TARGET_REGISTRY }}
        continue-on-error: true

      - name: 检查 Docker 登录成功
        if: ${{ steps.login.outcome == 'success' }}
        run: echo "Docker 登录成功"

      - name: 检查 Docker 登录失败
        if: ${{ steps.login.outcome != 'success' }}
        run: echo "Docker 登录失败"

      - name: 拉取、标记并推送 Docker 镜像
        id: pull_tag_push
        run: |
          ls
          return
          docker pull --platform ${{ github.event.inputs.ARCH }} grafana/grafana:9.3.16
          docker pull --platform ${{ github.event.inputs.ARCH }} jimmidyson/configmap-reload:v0.5.0
          docker pull --platform ${{ github.event.inputs.ARCH }} quay.io/brancz/kube-rbac-proxy:v0.14.0
          docker pull --platform ${{ github.event.inputs.ARCH }} quay.io/prometheus/alertmanager:v0.25.0
          docker pull --platform ${{ github.event.inputs.ARCH }} quay.io/prometheus/blackbox-exporter:v0.23.0
          docker pull --platform ${{ github.event.inputs.ARCH }} quay.io/prometheus-operator/prometheus-operator:v0.62.0
          docker pull --platform ${{ github.event.inputs.ARCH }} quay.io/prometheus/node-exporter:v1.5.0
          docker pull --platform ${{ github.event.inputs.ARCH }} quay.io/prometheus/prometheus:v2.41.0
          docker pull --platform ${{ github.event.inputs.ARCH }} registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.7.0
          docker pull --platform ${{ github.event.inputs.ARCH }} registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.10.0
          
          docker pull --platform ${{ github.event.inputs.ARCH }} docker.elastic.co/elasticsearch/elasticsearch:7.17.24
          docker pull --platform ${{ github.event.inputs.ARCH }} docker.elastic.co/kibana/kibana:7.17.24
          docker pull --platform ${{ github.event.inputs.ARCH }} docker.elastic.co/beats/filebeat:7.17.24
          
          
          
          docker tag grafana/grafana:9.3.16 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/grafana:${{ github.event.inputs.ARCH }}-9.3.16
          docker tag jimmidyson/configmap-reload:v0.5.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/configmap-reload:${{ github.event.inputs.ARCH }}-v0.5.0
          docker tag quay.io/brancz/kube-rbac-proxy:v0.14.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/kube-rbac-proxy:${{ github.event.inputs.ARCH }}-v0.14.0
          docker tag quay.io/prometheus/alertmanager:v0.25.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/alertmanager:${{ github.event.inputs.ARCH }}-v0.25.0
          docker tag quay.io/prometheus/blackbox-exporter:v0.23.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/blackbox-exporter:${{ github.event.inputs.ARCH }}-v0.23.0
          docker tag quay.io/prometheus-operator/prometheus-operator:v0.62.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/prometheus-operator:${{ github.event.inputs.ARCH }}-v0.62.0
          docker tag quay.io/prometheus/node-exporter:v1.5.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/node-exporter:${{ github.event.inputs.ARCH }}-v1.5.0
          docker tag quay.io/prometheus/prometheus:v2.41.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/prometheus:${{ github.event.inputs.ARCH }}-v2.41.0
          docker tag registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.7.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/kube-state-metrics:${{ github.event.inputs.ARCH }}-v2.7.0
          docker tag registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.10.0 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/prometheus-adapter:${{ github.event.inputs.ARCH }}-v0.10.0
          
          docker tag docker.elastic.co/elasticsearch/elasticsearch:7.17.24 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/elasticsearch:${{ github.event.inputs.ARCH }}-7.17.24
          docker tag docker.elastic.co/kibana/kibana:7.17.24 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/kibana:${{ github.event.inputs.ARCH }}-7.17.24
          docker tag docker.elastic.co/beats/filebeat:7.17.24 ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/filebeat:${{ github.event.inputs.ARCH }}-7.17.24
          
          
          
          
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/grafana:${{ github.event.inputs.ARCH }}-9.3.16
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/configmap-reload:${{ github.event.inputs.ARCH }}-v0.5.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/kube-rbac-proxy:${{ github.event.inputs.ARCH }}-v0.14.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/alertmanager:${{ github.event.inputs.ARCH }}-v0.25.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/blackbox-exporter:${{ github.event.inputs.ARCH }}-v0.23.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/prometheus-operator:${{ github.event.inputs.ARCH }}-v0.62.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/node-exporter:${{ github.event.inputs.ARCH }}-v1.5.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/prometheus:${{ github.event.inputs.ARCH }}-v2.41.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/kube-state-metrics:${{ github.event.inputs.ARCH }}-v2.7.0
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/prometheus-adapter:${{ github.event.inputs.ARCH }}-v0.10.0
          
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/elasticsearch:${{ github.event.inputs.ARCH }}-7.17.24
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/kibana:${{ github.event.inputs.ARCH }}-7.17.24
          docker push ${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/filebeat:${{ github.event.inputs.ARCH }}-7.17.24

         
          docker images
        continue-on-error: true

      - name: 检查镜像推送成功
        if: ${{ steps.pull_tag_push.outcome == 'success' }}
        run: echo "Docker 镜像推送成功"

      - name: 检查镜像推送失败
        if: ${{ steps.pull_tag_push.outcome != 'success' }}
        run: echo "Docker 镜像推送失败"
