name: 拉取镜像推送

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: '原镜像名称:版本'
        required: true
        default: '-'
      NEW_NAME:
        description: '同步后镜像名称:版本'
        required: true
        default: '-'
      TARGET_REGISTRY:
        description: '仓库地址'
        required: true
        default: 'registry.cn-hangzhou.aliyuncs.com'
      TARGET_REPOSITORY:
        description: '空间名称'
        required: true
        default: 'aopkcn'
      ARCH:
        description: '系统架构'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64
          - arm/v7
          - arm/v6
          - 386
          - s390x
          - ppc64le

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 处理文件
        id: pull_tag_push
        run: |
          for line in $(cat images.txt); do
            echo $line
          done
        continue-on-error: true

      - name: 执行结果-成功
        if: ${{ steps.pull_tag_push.outcome == 'success' }}
        run: echo "命令执行成功"

      - name: 执行结果-失败
        if: ${{ steps.pull_tag_push.outcome != 'success' }}
        run: echo "命令执行失败"
